// layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import ClientLayout from "./client-layout"; // Import ClientLayout
import { localFont } from './fonts';

export const metadata: Metadata = {
  title: "S Lanka Jewellery",
  description: "Generated by S Lanka Jewellery",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={localFont.className} style={localFont.style}>
        {/* Wrap the app with ClientLayout to ensure SessionProvider is available */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
